### ISSUE TITLE
全体管理

### ISSUE THREAD

**Issue by mihye1128** [camp-team/deer20201105#1]
## スケジュール
- [x] 10/29(木)   　基本機能実装完了
- [x] 10/31(土)   　メッセージ受付開始
- [x]  11/1(日)　　   デザイン・実装完了
- [x]  11/3(火)　　  テスト・最終確認
- [x]  11/4(水)　　  メッセージ受付最終締切
- [x]  11/5(木)　　  発表

### 開発担当（開発期間： 10/26 - 11/3）
- 管理画面UI & Firestore　@hide-a1
- 管理画面UI & Firestore & storage　@kkkkoki
- 管理画面UI & Auth & Firestore & direction　@mihye1128
- サービス画面UI & avatar　@yusukegunji & His girlfriend

### メッセージ募集連絡担当（受付期間： 10/31 - 11/4）
- 卒業生＆退会済メンバー　@chamaboy @yusukegunji @kkkkoki
- 在籍中メンバー　@hide-a1  @peyo  @mihye1128

### メッセージ参加者
CAMP メンタープラン 在籍メンバー ＆ OB・OG #30 

### 環境構築
- [x] Angular
- [x] Prettier
- [x] AngularMaterial
- [x] Firebase
- [x] AngularFire
- [x] layout
- [x] SCSS global import
- [x] Github Actions #8 
- [x] ng update #26 

### 画面作成
- [x] homeScreen #3 
- [x]  messageListScreen #4 
- [x] loginScreen #5 
- [x] settingsScreen #6 
- [x] notFoundScreen #7 

### 機能実装
- [x] AuthService / login() #9 @mihye1128 
- [x] AuthService / logout() #10  @mihye1128 
- [x] UserService / createUser() #11  @mihye1128 
- [x] UserService / getUsers() #12  @hide-a1 
- [x] UserService / getUser()・updateUser() #13 @kkkkoki 
- [x] UserService / deleteUser() #14   @mihye1128 
- [x] AuthGuard(←settingsScreen) #15   @mihye1128 
- [x] UserGuard(←loginScreen) #16   @mihye1128 

### デザイン作成
- [x] homeScreen #17 @yusukegunji 
- [x]  messageListScreen #18 @hide-a1 @mihye1128 
- [x] loginScreen #19 @mihye1128 
- [x] settingsScreen #20 @kkkkoki   @mihye1128 
- [x] notFoundScreen #21 @mihye1128 

## 設計
![image](https://user-images.githubusercontent.com/46749854/97600893-e4006580-1a4c-11eb-8073-9041dab8e0ba.png)
